name: Buscaminas
rules:
  - image: mina.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: tapado.png
    when:
      black: '*'
      blue: 1
      green: '*'
      red: 0
  - image: bandera.png
    when:
      black: '*'
      blue: '*'
      green: '*'
      red: 1
  - image: 1.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 0
  - image: 2.png
    when:
      black: 0
      blue: 0
      green: 2
      red: 0
  - image: 3.png
    when:
      black: 0
      blue: 0
      green: 3
      red: 0
  - image: 4.png
    when:
      black: 0
      blue: 0
      green: 4
      red: 0
  - image: 5.png
    when:
      black: 0
      blue: 0
      green: 5
      red: 0
  - image: 6.png
    when:
      black: 0
      blue: 0
      green: 6
      red: 0
  - image: 7.png
    when:
      black: 0
      blue: 0
      green: 7
      red: 0
  - image: 8.png
    when:
      black: 0
      blue: 0
      green: 8
      red: 0
  - image: linea.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 2
